-- generated by pyha 0.0.0 at 2017-03-01 00:53:26
library ieee;
    use ieee.fixed_pkg.all;

package ComplexTypes is
type complex_sfix0_17 is record
    real: sfixed(0 downto -17);
    imag: sfixed(0 downto -17);
end record;
function ComplexSfix(a, b: sfixed(0 downto -17)) return complex_sfix0_17;

end package;

package body ComplexTypes is
function ComplexSfix(a, b: sfixed(0 downto -17)) return complex_sfix0_17 is
begin
    return (a, b);
end function;

end package body;
