-- generated by pyha 0.0.0 at 2017-03-01 00:53:23
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;
    use ieee.fixed_float_types.all;
    use ieee.fixed_pkg.all;
    use ieee.math_real.all;

library work;
    use work.ComplexTypes.all;
    use work.PyhaUtil.all;
    use work.all;


package Conjugate_0 is



    type next_t is record
        outreg: complex_sfix0_17;
    end record;

    type self_t is record
        -- constants
        \_delay\: integer;

        outreg: complex_sfix0_17;
        \next\: next_t;
    end record;

    procedure \_pyha_constants_self\(self: inout self_t);

    procedure \_pyha_reset_self\(self: inout self_t);

    procedure \_pyha_update_self\(self: inout self_t);


    procedure main(self:inout self_t; x: complex_sfix0_17; ret_0:out complex_sfix0_17);
end package;

package body Conjugate_0 is
    procedure \_pyha_constants_self\(self: inout self_t) is
    begin
        self.\_delay\ := 1;

    end procedure;

    procedure \_pyha_reset_self\(self: inout self_t) is
    begin
        self.\next\.outreg := (real=>Sfix(0.0, 0, -17), imag=>Sfix(0.0, 0, -17));
        \_pyha_update_self\(self);
    end procedure;

    procedure \_pyha_update_self\(self: inout self_t) is
    begin
        self.outreg := self.\next\.outreg;
        \_pyha_constants_self\(self);
    end procedure;


    procedure main(self:inout self_t; x: complex_sfix0_17; ret_0:out complex_sfix0_17) is

    begin
        self.\next\.outreg.real := x.real;
        self.\next\.outreg.imag := resize(-x.imag, size_res=>x.imag);
        ret_0 := self.outreg;
        return;
    end procedure;
end package body;
