-- generated by pyha 0.0.0 at 2017-03-02 20:56:51
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;
    use ieee.fixed_float_types.all;
    use ieee.fixed_pkg.all;
    use ieee.math_real.all;

library work;
    use work.ComplexTypes.all;
    use work.PyhaUtil.all;
    use work.all;

-- Demo class, multiply and add coef to input
package Demo_0 is



    type next_t is record
        mult: sfixed(0 downto -17);
        add: sfixed(0 downto -17);
        coef_f: sfixed(0 downto -17);
    end record;

    type self_t is record
        -- constants
        \_delay\: integer;

        mult: sfixed(0 downto -17);
        add: sfixed(0 downto -17);
        coef_f: sfixed(0 downto -17);
        \next\: next_t;
    end record;

    procedure \_pyha_constants_self\(self: inout self_t);

    procedure \_pyha_reset_self\(self: inout self_t);

    procedure \_pyha_update_self\(self: inout self_t);

    -- Mulitply 'input' with self.coef
    procedure multiply(self:inout self_t; input: sfixed(0 downto -17); ret_0:out sfixed(0 downto -17));

    -- Add 'input' and self.coef
    procedure adder(self:inout self_t; input: sfixed(0 downto -17); ret_0:out sfixed(0 downto -17));


    procedure main(self:inout self_t; input: sfixed(0 downto -17); ret_0:out sfixed(0 downto -17); ret_1:out sfixed(0 downto -17));
end package;

package body Demo_0 is
    procedure \_pyha_constants_self\(self: inout self_t) is
    begin
        self.\_delay\ := 1;

    end procedure;

    procedure \_pyha_reset_self\(self: inout self_t) is
    begin
        self.\next\.mult := Sfix(0.0, 0, -17);
        self.\next\.add := Sfix(0.0, 0, -17);
        self.\next\.coef_f := Sfix(0.1, 0, -17);
        \_pyha_update_self\(self);
    end procedure;

    procedure \_pyha_update_self\(self: inout self_t) is
    begin
        self.mult := self.\next\.mult;
        self.add := self.\next\.add;
        self.coef_f := self.\next\.coef_f;
        \_pyha_constants_self\(self);
    end procedure;



    -- Mulitply 'input' with self.coef
    procedure multiply(self:inout self_t; input: sfixed(0 downto -17); ret_0:out sfixed(0 downto -17)) is

    begin
        self.\next\.mult := resize(input * self.coef_f, size_res=>input, round_style=>fixed_truncate);
        ret_0 := self.mult;
        return;
    end procedure;

    -- Add 'input' and self.coef
    procedure adder(self:inout self_t; input: sfixed(0 downto -17); ret_0:out sfixed(0 downto -17)) is

    begin
        self.\next\.add := resize(input + self.coef_f, size_res=>input);
        ret_0 := self.add;
        return;
    end procedure;


    procedure main(self:inout self_t; input: sfixed(0 downto -17); ret_0:out sfixed(0 downto -17); ret_1:out sfixed(0 downto -17)) is
        variable mult: sfixed(0 downto -17);
        variable add: sfixed(0 downto -17);
    begin
        multiply(self, input, ret_0=>mult);
        adder(self, input, ret_0=>add);
        ret_0 := mult;
        ret_1 := add;
        return;

    end procedure;
end package body;
