-- generated by pyha 0.0.0 at 2017-02-26 21:27:17
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;
    use ieee.fixed_float_types.all;
    use ieee.fixed_pkg.all;
    use ieee.math_real.all;

library work;
    use work.ComplexTypes.all;
    use work.PyhaUtil.all;
    use work.all;

-- Simple module that has one Sfix register
package A0_0 is



    type next_t is record
        reg: sfixed(0 downto -17);
    end record;

    type self_t is record
        -- constants
        \_delay\: integer;

        reg: sfixed(0 downto -17);
        \next\: next_t;
    end record;

    procedure \_pyha_constants_self\(self: inout self_t);

    procedure \_pyha_reset_self\(self: inout self_t);

    procedure \_pyha_update_self\(self: inout self_t);


    procedure main(self:inout self_t; \new\: sfixed(0 downto -17); ret_0:out sfixed(0 downto -17));
end package;

package body A0_0 is
    procedure \_pyha_constants_self\(self: inout self_t) is
    begin
        self.\_delay\ := 1;

    end procedure;

    procedure \_pyha_reset_self\(self: inout self_t) is
    begin
        self.\next\.reg := Sfix(0.1, 0, -17);
        \_pyha_update_self\(self);
    end procedure;

    procedure \_pyha_update_self\(self: inout self_t) is
    begin
        self.reg := self.\next\.reg;
        \_pyha_constants_self\(self);
    end procedure;




    procedure main(self:inout self_t; \new\: sfixed(0 downto -17); ret_0:out sfixed(0 downto -17)) is

    begin
        -- give new value to reg
        self.\next\.reg := \new\;
        ret_0 := self.reg;
        return;

    end procedure;
end package body;
