-- generated by pyha 0.0.0 at 2017-02-26 21:27:17
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;
    use ieee.fixed_float_types.all;
    use ieee.fixed_pkg.all;
    use ieee.math_real.all;

library work;
    use work.ComplexTypes.all;
    use work.PyhaUtil.all;
    use work.all;

-- This module has list of registers and submodules
package A2_0 is

    type A1_0_list_t is array (natural range <>) of A1_0.self_t;
    type sfixed00_list_t is array (natural range <>) of sfixed(0 downto 0);

    type next_t is record
        sub_list: A1_0_list_t(0 to 1);
        sfix_list: sfixed00_list_t(0 to 11);
        sum: sfixed(0 downto 0);
    end record;

    type self_t is record
        -- constants
        \_delay\: integer;

        sub_list: A1_0_list_t(0 to 1);
        sfix_list: sfixed00_list_t(0 to 11);
        sum: sfixed(0 downto 0);
        \next\: next_t;
    end record;

    procedure \_pyha_constants_self\(self: inout self_t);

    procedure \_pyha_reset_self\(self: inout self_t);

    procedure \_pyha_update_self\(self: inout self_t);


    procedure main(self:inout self_t; \new\: sfixed(0 downto -17); ret_0:out sfixed(0 downto -17); ret_1:out sfixed(0 downto -17));
end package;

package body A2_0 is
    procedure \_pyha_constants_self\(self: inout self_t) is
    begin
        self.\_delay\ := 2;
        A1_0.\_pyha_constants_self\(self.sub_list(0));
        A1_0.\_pyha_constants_self\(self.sub_list(1));
    end procedure;

    procedure \_pyha_reset_self\(self: inout self_t) is
    begin
        self.sub_list(0).submodule.\next\.reg := Sfix(0.1, 0, -17);
        self.sub_list(0).\next\.reg := Sfix(0.98, 0, -17);
        self.sub_list(1).submodule.\next\.reg := Sfix(0.2, 0, -17);
        self.sub_list(1).\next\.reg := Sfix(0.98, 0, -17);
        self.\next\.sfix_list := (Sfix(0.0, 0, 0), Sfix(0.0, 0, 0), Sfix(0.0, 0, 0), Sfix(0.0, 0, 0), Sfix(0.0, 0, 0), Sfix(0.0, 0, 0), Sfix(0.0, 0, 0), Sfix(0.0, 0, 0), Sfix(0.0, 0, 0), Sfix(0.0, 0, 0), Sfix(0.0, 0, 0), Sfix(0.0, 0, 0));
        self.\next\.sum := Sfix(0.0, 0, 0);
        \_pyha_update_self\(self);
    end procedure;

    procedure \_pyha_update_self\(self: inout self_t) is
    begin
        A1_0.\_pyha_update_self\(self.sub_list(0));
        A1_0.\_pyha_update_self\(self.sub_list(1));
        self.sfix_list := self.\next\.sfix_list;
        self.sum := self.\next\.sum;
        \_pyha_constants_self\(self);
    end procedure;




    procedure main(self:inout self_t; \new\: sfixed(0 downto -17); ret_0:out sfixed(0 downto -17); ret_1:out sfixed(0 downto -17)) is
        variable r1: sfixed(0 downto -17);
        variable r2: sfixed(0 downto -17);
    begin
        -- call submodules functions
        for \_i_\ in self.sub_list'range loop
            A1_0.main(self.sub_list(\_i_\), \new\, ret_0=>r1, ret_1=>r2);

        end loop;
        ret_0 := r1;
        ret_1 := r2;
        return;

    end procedure;
end package body;
