-- generated by pyha 0.0.0 at 2017-02-25 14:42:09
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;
    use ieee.fixed_float_types.all;
    use ieee.fixed_pkg.all;
    use ieee.math_real.all;

library work;
    use work.ComplexTypes.all;
    use work.PyhaUtil.all;
    use work.all;


package Register_0 is



    type next_t is record
        reg: integer;
    end record;

    type self_t is record
        -- constants
        \_delay\: integer;

        reg: integer;
        \next\: next_t;
    end record;

    procedure \_pyha_constants_self\(self: inout self_t);

    procedure \_pyha_reset_self\(self: inout self_t);

    procedure \_pyha_update_self\(self: inout self_t);

    -- Hardware model, convertable to VHDL
    procedure main(self:inout self_t; inp: integer; ret_0:out integer);
end package;

package body Register_0 is
    procedure \_pyha_constants_self\(self: inout self_t) is
    begin
        self.\_delay\ := 1;

    end procedure;

    procedure \_pyha_reset_self\(self: inout self_t) is
    begin
        self.\next\.reg := 0;
        \_pyha_update_self\(self);
    end procedure;

    procedure \_pyha_update_self\(self: inout self_t) is
    begin
        self.reg := self.\next\.reg;
        \_pyha_constants_self\(self);
    end procedure;

    -- Hardware model, convertable to VHDL
    procedure main(self:inout self_t; inp: integer; ret_0:out integer) is

    begin
        self.\next\.reg := inp;
        -- wat
        ret_0 := self.reg;
        return;
    end procedure;
end package body;
